%YAML:1.0
---
color:
    hue_tol: 5
    sat_tol: 75
    rect_min_area: 200.0
    circle_min_area: 2.0
    ball_min_area: 15.0

camera:
    width: 800
    height: 600
    fps: 30

window:
    name: window
    delay: 40
